language: objective-c
osx_image: xcode9.2
env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
    - WORKSPACE=Embassy.xcworkspace
    - IOS_FRAMEWORK_SCHEME="Embassy-iOS"
    - IOS_SDK=iphonesimulator11.2
    - MACOS_FRAMEWORK_SCHEME="Embassy-macOS"
    - MACOS_SDK=macosx10.13
  matrix:
    - DESTINATION="OS=11.2,name=iPhone 6S"     SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"
    - DESTINATION="arch=x86_64"                SCHEME="$MACOS_FRAMEWORK_SCHEME"   SDK="$MACOS_SDK"

script:
  - >
    set -o pipefail &&
    xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK"
    -destination "$DESTINATION" -configuration Debug
    ONLY_ACTIVE_ARCH=NO test | xcpretty -c;
